apiVersion: skaffold/v2alpha4
kind: Config
# Enforce SKaffold to use Jib
build:
  artifacts:
  - image: asia.gcr.io/sphong-kuber/sample-admin
    context: .
    jib :
      project: sample-admin
    sync:
      manual:
        - src : 'sample-admin/src/**/*.java'
          dest : .
  - image: asia.gcr.io/sphong-kuber/sample-api
    context: .
    jib:
      project: sample-api
    sync:
      manual:
        - src: 'sample-api/src/**/*.java'
          dest: .
  - image: asia.gcr.io/sphong-kuber/sample-common
    context: .
    jib:
      project: sample-common
    sync:
      manual:
        - src: 'sample-common/src/**/*.java'
          dest: .
  # Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/**/*.yml